apiVersion: operator.ibm.com/v1alpha1
kind: HelmRepo
metadata:
  name: helm-repo
  labels:
    app.kubernetes.io/instance: helm-repo
    app.kubernetes.io/managed-by: helmrepos.operator.ibm.com
    app.kubernetes.io/name: helm-repo
spec:
  helmrepo:
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
  replicaCount: 1